{
 "title": "Long Run Test 1",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "k8s_cluster", "label": "Kubernetes Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"coredns\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Churn Validation Failures",
   "type": "graph",
   "description": "Churn is created by adding and deleting Services and Endpoints.  Each add/delete is validated via a DNS lookup.  Validation failures are reported here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubernoisy_validation_fail_count_total",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Churn Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubernoisy_action_count_total[5m])",
     "legendFormat": "{{object}} {{action}}"
    }
   ]
  },
  {
   "title": "Queries Lost",
   "type": "graph",
   "description": "Queries sent by the dnsdrone that did not receive a response from CoreDNS within the timeout (default 5s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnsdrone_response_lost_count_total[5m])) / sum(rate(dnsdrone_request_count_total[5m]))",
     "legendFormat": "queries lost"
    }
   ]
  },
  {
   "title": "Latency Reported by CoreDNS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(coredns_dns_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(coredns_dns_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_sum[5m])) / sum(rate(coredns_dns_request_duration_seconds_count[5m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "QPS Sent (dnsdrone)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dnsdrone_request_count_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Received per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(coredns_dns_request_count_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS Received (dnsdrone)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnsdrone_response_count_total[5m]))",
     "legendFormat": "all responses"
    },
    {
     "expr": "sum by (rcode) (rate(dnsdrone_response_count_total[5m]))",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "coredns_cache_size", "legendFormat": "{{instance}} {{type}}" }
   ]
  },
  {
   "title": "Latency Reported by Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dnsdrone_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dnsdrone_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(dnsdrone_request_duration_seconds_sum[5m])) / sum(rate(dnsdrone_request_duration_seconds_count[5m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "CoreDNS Cache Hit  Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total[5m])) / sum(rate(coredns_dns_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Churn Latency (Inc TTL)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubernoisy_validation_duration_seconds_bucket{action=\"add\"}[5m])) by (le))",
     "legendFormat": "Add 95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(kubernoisy_validation_duration_seconds_bucket{action=\"add\"}[5m])) by (le))",
     "legendFormat": "Add 50th"
    },
    {
     "expr": "sum(rate(kubernoisy_validation_duration_seconds_sum{action=\"add\"}[5m])) / sum(rate(kubernoisy_validation_duration_seconds_count{action=\"add\"}[5m]))",
     "legendFormat": "Add Mean"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubernoisy_validation_duration_seconds_bucket{action=\"delete\"}[5m])) by (le))",
     "legendFormat": "Delete 95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(kubernoisy_validation_duration_seconds_bucket{action=\"delete\"}[5m])) by (le))",
     "legendFormat": "Delete 50th"
    },
    {
     "expr": "sum(rate(kubernoisy_validation_duration_seconds_sum{action=\"delete\"}[5m])) / sum(rate(kubernoisy_validation_duration_seconds_count{action=\"delete\"}[5m]))",
     "legendFormat": "Delete Mean"
    }
   ]
  }
 ]
}